dist: xenial
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: XXtxOBe47ZU6ngVh/6kpikrUSMCHYk1kiXAkJTVJymNNkldnvosHFhDONgpw6KDRF1aWk7bUHugNgWCYm5hTaChCvRKGDoI/iHrCuw32N2dSzC+e40heXjQ8Iop0tgkzjeEDqJi2aHtyx3l/LUvcYt7pDm8M+5UlslxbnAE1zQaLsWn/1tG8RkMR84NI4Fa+mQFMwkAbBi+HRdFRm+8BhIpaHcRHTiAxd613oQEatfUqvxaOZ2jh2h2e+KbpK1s0AtF/zKCTBb2G6CezmXNuodc6r9CU/GxfpEHiOkW7UHTrKoFUoLW0aNRghmCjiU+q9tZ8OTzw6dhF7wgtOjc2SOvqODiQnz1TU5PYwWEYhqVhIf6fmFSxjCkzEqKfEv6D/zYbWz1aqzBROqqzVN3ufErbRsZvbAPgpPNczMAkvt2k+3EdJSY8bofKDwmjv1rq80pJM8eWEsUsklpngopcJcvKZE/KL+XeVq13PzHQcGxOATvETBm1HPxU++mUK1j5STJOuaXad/dHM2h7sLACZ6Hpmv8O/l0JCCe3HJrZFgDF0eSXHlePERZDN6Mr4NJGbNiQ8K8fxDF077O3jKOH7GpaVasPE/bl+Ja4KQ3LynAUhLDps5sQJ+1xvqH1wN5uvQqwIGJ4uCuQh+i+S7wP83FENxMJ8Or+HULTPGp1XjA=
language: python
python:
- '3.7'
before_install:
- pip install --upgrade pytest
install:
- pip install ."[test,test]"
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=dict_hash --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- sonar-scanner
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: C+YfHCkWm5z1YNeeFZtLXnTTTmz7D9FEMRueNOCK/ALrJVJOgLiVeM/xVGupTxyIjBbyEuznkNdDuV+WvZK3wcVBgNwv3QMPJs6T8VcYIcilDYrdFgtk+6xhkFAPa6iwYRO4J8rsOIlJE0mbLLQvDG/fHPoSy9KeAeI7hnBuJHt07KejvSz5/d7pepEUo2B40/9cvfimIXEPrcpCaphpFqz/5ROrJo6FHsLIU953J+3l9Im/vBnVZUJZqwh+/NmDyXTSek9n5oUo7VdcsEWIRiHajoEauaAFZU4mNRr8oI+P6QgnCkcntFPgJCVKizo9Pt5xs39M+2GRmGs/DIk+f7zPdJnNfA1zdctofqcZrJmvba+oiB+QKooOJQysfA4+eBMpx/ltn12hwzmLRKN2H4sHuyJiEbj1KfaUYz1chIeheclQ4IzBA8VBdPDy0Ds8CJMiJnUJvUS8I6Ol0Pk/Hsnb1mf2O/Ju99PQxRylvv/PSHIjFK/EumE8e9qFHKhtkMk4UnXSTkNBWkZArOa7GfVEOd9OHtOc2b3Qx30KGrCEjdsA9prfFupL8sXQytMh2amuoHuwezCuI7jos5HkHkG4n5kTjFWqFfg8ixYCajlFX9S8R/pKDhn/uTxzJSbkA0rWF3UU4elLRT3jp3lOKNEYnFvtfFrZ+BUG4EBF3FM=
  - secure: APjsoZZvRvD7InWdDN1JXU+TZk7h/mSqgzVnrAw0IE7kSczMdK79s4ChXn8V9hJpIcm88C06tRZxbOFM3/I7BSIYKzLJclYfR+e5Bt0UgJhCK9Dwie47uEXtjJaGz9RycT+Ztf6jr162+vFCpTwtZeTQLWYPesi1W6PcgAfZqnjMFI1R1rdw2D4GXSG0fu/uMsin4nJKkVPqqL22q9CQC+tBPOP0tIKKWX2+j75AEV7q0PyQM4qaduuFWtvCZX6exrmR2SzMvO0uI90f3rL4HBDtbGJczepYSUfuxAGjdKtNoUfbU8vWrFp1qI35NLEUbpJkqywPKq/kzUy+vDka/nowJQzYqHaslC776Qogn3RQt5kw8HXLhUzxsgOVDh/XHOiFCHPvOKlKUTBKMcUBMjijmAy/eqXCWy9RdHWGaImYyyMSff0QRq+Jhb95SLIWraAA3PAzjFjkTqHkMaLGL/l10wRgERJVnbAmeYGtRz1f6qo/rkqkWpta5dseDM+3oV3OTaP4VrqD5vJNU+4XODY1eTM1pjiyvaXv3IJQNFoxxuFzqFfH6L5JjVTnoybDHmmIAh7RZCaqkx5EbdxfzjRLHzkHbqbBx8r9SJYB3lx4DJFm1koHunJAKRd4QkSOQgJUnE8HB30iEVztA/431eNenRTF58opbQfitATH/2Q=
