name: MyPy Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install ".[test]"
          pip install pandas pandas-stubs numpy polars numba
          pip install mypy  # Ensure mypy is installed

      - name: Run MyPy
        run: mypy dict_hash/
