name: Python Package CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        pandas-version: ["pandas<2.0", "pandas>=2.0"]
        numpy-version: ["numpy<2.0", "numpy>=2.0"]
        exclude:
          - python-version: "3.7"
            pandas-version: "pandas>=2.0"
          - python-version: "3.7"
            numpy-version: "numpy>=2.0"
          - python-version: "3.8"
            pandas-version: "pandas>=2.0"
          - python-version: "3.8"
            numpy-version: "numpy>=2.0"
          - python-version: "3.9"
            pandas-version: "pandas<2.0"
          - python-version: "3.10"
            pandas-version: "pandas<2.0"
          - python-version: "3.11"
            pandas-version: "pandas<2.0"
          - python-version: "3.11"
            numpy-version: "numpy>=2.0"
          - python-version: "3.12"
            pandas-version: "pandas<2.0"
          - python-version: "3.12"
            numpy-version: "numpy<2.0"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install polars numba
        pip install black ".[test]"

    - name: Check code is formatted
      run: black --check .

    - name: Run tests with default dependencies
      run: pytest

    - name: Run tests with Numpy
      run: |
        pip uninstall -y numpy
        pip install "${{ matrix.numpy-version }}"
        pytest
    
    - name: Run tests with Pandas
      run: |
        pip uninstall -y pandas
        pip install "${{ matrix.pandas-version }}"
        pytest

    - name: Build package
      run: |
        python -m pip install wheel
        python setup.py sdist bdist_wheel
